### ISSUE TITLE
Reincorporate the switch statement [IMPORTANT]

### ISSUE THREAD

**Issue by EmilSoderlind** [HedbergMartin/Darken#1]
Dear Mr. Hedberg,

Could you perhaps please get your shit together and reincorporate the brilliant switch statement once again, bitch.

XoXo,
SkruvdragarN

**Comment by HedbergMartin** [comment]
This is a stupid request that would ruin the code even more than your previous contribution. But not as bad as having the read and write in the same method. Therefore I am closing this issue.
